### ISSUE TITLE
Old Sol submodule points to an invalid commit

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/lua-bench#10]
Probably something uncommitted or internal, but the old-sol submodule (`vendor/old-sol`) points to a commit that cannot be found in the public repo.

This can be currently "fixed" by checking out to a commit manually and then renaming stuff to `old_sol` locally, but I think it should be fixed regardless.

**Comment by OrfeasZ** [comment]
After further investigation it looks like the submodule points to a commit that was in a branch that was (probably) deleted.

**Comment by ThePhD** [comment]
This should be fixed now: I was pointing to Rapptz/sol and not ThePhD/sol for the commit, so it wasn't finding it. It should be alright now.
