### ISSUE TITLE
add lualite

### ISSUE THREAD

**Issue by user1095108** [ThePhD/lua-bench#12]
Can you add my library, lualite, into your bench?

https://github.com/user1095108/lualite.git

**Comment by ThePhD** [comment]
I would if you had more complete documentation. How do I handle tables with your library? Is it just for modules? How do I bind member variables (or can I just not)? What is with all of these casts for member functions? Is there optional support?

Do I need to write a get/set for every single type I want to bind (e.g., for `point` in `testclass.cpp`)? Or is that just for easier interop for that single type?

Tou have an example of usage in the readme, but _where is the class definition that all of this comes from_? Or is that just a straight rip from `testclass.cpp`? I know docs are hard but you can't have minimalist docs and expect me to be happy at doing all the gruntwork for benching your library. =/

**Comment by user1095108** [comment]
There is no way to handle member variables, since this was supposed to be handled by properties. Tables are just for modules, there is no C++ wrapper for them. Casts are there because of overloads. There is support for variadic arguments, if you want an example and can write one for you. Yes, you need a get/set pair for every single type, but it's better if you look into the library source to see how it's done better. Yes, it's a single class definition, you can see it in action in the testlualite.cpp.

I can write up everything you need.

**Comment by user1095108** [comment]
check lualite::any for optional support :)

**Comment by ThePhD** [comment]
lualite busts in Visual Studio 2015 when I try to run the tests, with a error message based on evaluating
`#if __cplusplus < 201402L`. While this makes sense for g++ and clang++, VC++ probably supports everything you need, so this check is deal breaking.

Sorry. If you want, when you fix the library you can edit the file here: https://github.com/ThePhD/lua-bench/blob/master/lua%20bench/src/lualite.cpp

There's an `#if 0` around the whole thing, and then after that there's a bunch of commented out lines for what is supposed to be tested (given as an example using sol2). You're welcome to use that as a guideline, or look at the [plain C implementation](https://github.com/ThePhD/lua-bench/blob/master/lua%20bench/src/plain_c.cpp) as well to figure out how things get benchmarked.
