### ISSUE TITLE
Contact all library authors about paper and results

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/lua-bench#3]
Make sure they're in the loop and get their feedback about the feature table and all.

- [x] luwra - contacted, received response, edited
- [x] Selene - contacted, received response, edited
- [ ] luacppinterface - contacted, received preliminary response, waiting for full read
- [x] OOLua - contacted, received response, edited
- [x] luawrapper - contacted, received response, edited (author is actually just maintainer: not going to improve luwrapper anytime soon)
- [x] lua-intf - contacted, received response, edited paper
- [ ] kaguya - contacted
- [ ] lua-api-pp - contacted, received response, working on sending back response + editing paper + getting clarity

Not included: 
- SLB3 (dead library)
- luabind (Rasterbar gave up on it, too many forks, who the fuck do we know "owns" the most up-to-date/best version?)
- sol2 (that's me)
- Lua (they're not really going to care about this, I don't think? And who do I e-mail anyways?)
- SWIG (there's at least 8 people running that thing and while there is one person who handles the Lua module... would they care in particular? We haven't presented any novel information about SWIG here...)

**Comment by ThePhD** [comment]
Have edited lua-api-pp work, but parts of it still don't work.

**Comment by aDevilInMe** [comment]
As far as I can tell from looking at the source and reading the docs, Sol does not use error checking by default; i.e. SOL_SAFE_USERTYPE and SOL_CHECK_ARGUMENTS. It would be interesting, at least to me, to see OOLua compiled with the same lack of checking. This can be acheived by setting OOLUA_RUNTIME_CHECKS_ENABLED to zero in oolua_config.h [1] or by adding the define to the vcxproj in PreprocessorDefinitions. 
Cheers Liam


[1] https://github.com/elite-lang/oolua/blob/43488e3933fe0b88708a42856629c3641c9a51fa/include/oolua_config.h#L101

**Comment by ThePhD** [comment]
I'll be sure to add that in when I run the new benchmark numbers.

**Comment by ThePhD** [comment]
@aDevilInMe There is an error in VC++ when those defines are put in to take out runtime checks. There's an initial declaration of a function without inline, but when there's no runtime checks another inline declaration + definition is made in a header file. This triggers an ODR violation (at least in VC++).

I believe the proper fix would be using the define earlier to make only a single declaration / definition available to the compiler (from class_from_stack.h, line 88) like so:

```` cpp
#if OOLUA_CHECK_EVERY_USERDATA_IS_CREATED_BY_OOLUA == 0
		inline bool index_is_userdata(lua_State* vm, int index, Lua_ud*& ud)
		{
			ud = static_cast<Lua_ud *>(lua_touserdata(vm, index));
			return ud != 0;
		}
#else
		bool index_is_userdata(lua_State* vm, int index, Lua_ud*& ud);
#endif
````

**Comment by aDevilInMe** [comment]
The inline specifier does not create a ODR violation. The macros for OOLua must be available for the static library and also the executable and I suspect you have only made it available for the executable. The easiest way to do this is via oolua_config.h before compiling the static library. If you are still having a problem, please inform me how you specified them and which version of VC++ you are using. Thanks

**Comment by ThePhD** [comment]
@aDevilInMe You're right; I was doing something wrong, so I clean my build settings, reverted changes and tried again. It worked out and now OOLUA_RUNTIME_CHECKS_ENABLED is set to 0.

**Comment by ThePhD** [comment]
Seems like Kaguya author and lua-api-pp author are too busy to get back to me. Granted, they're working on things much more interesting than the binding glues, so I'll just have to leave it be.
